// Code generated by ent, DO NOT EDIT.

package tag

const (
	// Label holds the string label denoting the tag type in the database.
	Label = "tag"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTagStr holds the string denoting the tagstr field in the database.
	FieldTagStr = "tag_str"
	// EdgeTagArticle holds the string denoting the tagarticle edge name in mutations.
	EdgeTagArticle = "tagArticle"
	// Table holds the table name of the tag in the database.
	Table = "tags"
	// TagArticleTable is the table that holds the tagArticle relation/edge. The primary key declared below.
	TagArticleTable = "article_tags"
	// TagArticleInverseTable is the table name for the Article entity.
	// It exists in this package in order to avoid circular dependency with the "article" package.
	TagArticleInverseTable = "articles"
)

// Columns holds all SQL columns for tag fields.
var Columns = []string{
	FieldID,
	FieldTagStr,
}

var (
	// TagArticlePrimaryKey and TagArticleColumn2 are the table columns denoting the
	// primary key for the tagArticle relation (M2M).
	TagArticlePrimaryKey = []string{"article_id", "tag_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
